require('dotenv').config();
const {auditLog,auditLoginAttempt}=require('./middleware/audit');
const {sanitizeInputs}=require('./middleware/validate');
const {checkAllTokens}=require('./utils/tokenHealth');
const express=require('express');
const cors=require('cors');
const helmet=require('helmet');
const rateLimit=require('express-rate-limit');
const path=require('path');
const db=require('./db');
const app=express();
app.set('trust proxy', 1);
const PORT=process.env.PORT||3000;
app.use(helmet({contentSecurityPolicy:false}));
app.use(cors({origin:process.env.ALLOWED_ORIGIN||'*',credentials:true}));
app.use(express.json({ limit: '1mb' }));
app.use('/api/auth',rateLimit({windowMs:15*60*1000,max:20,message:{error:'Muitas tentativas.'}}));
app.use('/api/',rateLimit({windowMs:60*1000,max:200}));
app.use('/api/auth',require('./routes/auth'));
app.use('/api/accounts',require('./routes/accounts'));
app.use('/api/meta',require('./routes/meta'));
app.use('/api/admin',require('./routes/admin'));
app.use('/api/webhook',require('./routes/webhooks'));
app.use('/api/push',require('./routes/push').router);
app.get('/api/health',(req,res)=>res.json({status:'ok'}));
app.use(express.static(path.join(__dirname,'../frontend')));
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'../frontend/index.html')));
db.init();
app.listen(PORT,()=>console.log(`\n⚡ Pulse Ads rodando na porta ${PORT}\n`));
